name: Deploy Cloud Functions
on:
 workflow_dispatch:
 push:
   branches:
     - main
   paths:
     - 'functions/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check Bash version
        run: bash --version
      - name: Install Bash
        run: sudo apt-get update && sudo apt-get install -y bash
      - name: List working directory contents
        run: ls -la /home/runner/work/test-scheduleds/test-scheduleds/functions
      - name: Create SA key
        run: echo "GCP_SA_KEY=${{ secrets.MY_PRIVATE_KEY }}" > $HOME/gcloud.json
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:v11.24.1
        with:
          args: deploy --force --only functions:src -P ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}