name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Firebase CLI
        uses: FirebaseExtended/action-configure-firebase@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          token: ${{ secrets.MY_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:v11.24.1
        with:
          args: deploy --force --only functions:src -P ${{ secrets.FIREBASE_PROJECT_ID }}
env:
  RUNNER_TOOL_CACHE: node
  NODE_VERSION: 14.x
