 - name: Create SA key
   run: echo '${{ secrets.MY_PRIVATE_KEY }}' > $HOME/gcloud.json
 - name: Deploy Cloud Functions
   run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json