name: Deploy Cloud Functions
on:
 workflow_dispatch:
 push:
   branches:
     - main
   paths:
     - 'functions/**'
jobs:
 build_and_deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: 16
     - name: Create SA key
       run: echo '${{ secrets.MY_PRIVATE_KEY }}' > $HOME/gcloud.json
     - name: Deploy to Firebase
       uses: docker://w9jds/firebase-action:v11.24.1
       with:
          args: deploy --force --only functions:sheets-feeder -P ${{ secrets.FIREBASE_PROJECT_ID }}